### ISSUE TITLE
physicsEngine.getWorld() is undefined

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#115]
```
   beep  - starting game controller for channel (Ewich)

/home/jeena/chuck/chuck.js/app/Game/Core/GameObjects/GameObject.js:15
        this.body = physicsEngine.getWorld().CreateBody(def);
                                             ^
TypeError: Cannot call method 'CreateBody' of undefined
    at new GameObject (/home/jeena/chuck/chuck.js/app/Game/Core/GameObjects/GameObject.js:15:46)
    at GameObject.Tile (/home/jeena/chuck/chuck.js/app/Game/Core/GameObjects/Tile.js:15:13)
    at Level.createTiles (/home/jeena/chuck/chuck.js/app/Game/Core/Loader/Level.js:60:55)
    at Level.TiledLevel.createTiles (/home/jeena/chuck/chuck.js/app/Game/Core/Loader/TiledLevel.js:145:38)
    at Level.TiledLevel.setup (/home/jeena/chuck/chuck.js/app/Game/Core/Loader/TiledLevel.js:108:53)
    at /home/jeena/chuck/chuck.js/app/Game/Core/Loader/Level.js:28:18
    at /home/jeena/chuck/chuck.js/app/Game/Channel/Loader/Level.js:22:5
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
trelkovky is cheating.
trelkovky is cheating.
trelkovky is cheating.
trelkovky is cheating.
trelkovky is cheating.
   beep  - HTTP Server serves index

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:406:26)
    at PipeToChannel.send (/home/jeena/chuck/chuck.js/app/Server/PipeToChannel.js:42:13)
    at User.onDisconnect (/home/jeena/chuck/chuck.js/app/Server/User.js:48:26)
    at Socket.emit [as $emit] (events.js:95:17)
    at Socket.onDisconnect (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/socket.js:153:10)
    at SocketNamespace.handleDisconnect (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/namespace.js:229:46)
    at Manager.onClientDisconnect (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/manager.js:481:27)
    at WebSocket.Transport.end (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/transport.js:467:20)
    at Parser.<anonymous> (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/transports/websocket/hybi-16.js:52:10)
    at Parser.emit (events.js:92:17)


Error: channel closed
    at process.target.send (child_process.js:406:26)
    at PipeToServer.send (/home/jeena/chuck/chuck.js/app/Game/Channel/PipeToServer.js:38:22)
    at NotificationCenter.trigger (/home/jeena/chuck/chuck.js/app/Lib/Utilities/NotificationCenter.js:214:29)
    at User.sendControlCommand (/home/jeena/chuck/chuck.js/app/Game/Channel/User.js:64:9)
    at User.sendGameCommand (/home/jeena/chuck/chuck.js/app/Game/Channel/User.js:70:18)
    at Channel.broadcastGameCommand (/home/jeena/chuck/chuck.js/app/Game/Channel/Channel.js:187:32)
    at NotificationCenter.trigger (/home/jeena/chuck/chuck.js/app/Lib/Utilities/NotificationCenter.js:214:29)
    at GameController.updateWorld (/home/jeena/chuck/chuck.js/app/Game/Channel/GameController.js:110:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
npm ERR! chuck.js@0.1.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the chuck.js@0.1.0 start script.
npm ERR! This is most likely a problem with the chuck.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chuck.js
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.9.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/jeena/chuck/chuck.js
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jeena/chuck/chuck.js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jeena** [comment]
This didn't happen in Alpha 2 testing anymore, we assume that this has been fixed by the Assert stuff we implemented.
