### ISSUE TITLE
m_collideconnected of null Error

### ISSUE THREAD

**Issue by logsol** [logsol/chuck.js#96]
We are still encountering this box2d issue. it is rare, therefore i made a screenshot of the issue, to help track it down. Maybe it will disappear once we finish our asm box2d branch.

I think this was what was also happening to the skateboard, it's pushing the framerate to 1 fps and the cpu fan comes on.

![screen shot 2015-01-14 at 16 41 55](https://cloud.githubusercontent.com/assets/692826/5741619/80b76a4c-9c0c-11e4-8c5d-7b0327021894.png)

**Comment by logsol** [comment]
to me this happened, when I used "F" to grab, than the throwing thing got out of sync or something, trying to destroy a joint that's not there anymore.

**Comment by logsol** [comment]
probably just should check on all joints if they are still connected before trying to delete them...

**Comment by jeena** [comment]
This also happens on the server:

```
home/jeena/chuck/chuck.js/app/Lib/Vendor/Box2D.js:5838
      var collideConnected = j.m_collideConnected;
                              ^
TypeError: Cannot read property 'm_collideConnected' of null
    at b2World.DestroyJoint (/home/jeena/chuck/chuck.js/app/Lib/Vendor/Box2D.js:5838:31)
    at GameObject.Doll.throw (/home/jeena/chuck/chuck.js/app/Game/Core/GameObjects/Doll.js:361:30)
    at Player.throw (/home/jeena/chuck/chuck.js/app/Game/Core/Player.js:92:24)
    at Player.handAction (/home/jeena/chuck/chuck.js/app/Game/Channel/Player.js:41:27)
    at Player.handActionRequest (/home/jeena/chuck/chuck.js/app/Game/Channel/Player.js:29:15)
    at PlayerController.handActionRequest (/home/jeena/chuck/chuck.js/app/Game/Channel/Control/PlayerController.js:36:34)
    at PlayerController.applyCommand (/home/jeena/chuck/chuck.js/app/Game/Channel/Control/PlayerController.js:31:27)
    at User.onGameCommand (/home/jeena/chuck/chuck.js/app/Game/Channel/User.js:52:42)
    at Object.Helper.applyCommand (/home/jeena/chuck/chuck.js/app/Lib/Utilities/Protocol/Helper.js:36:32)
    at /home/jeena/chuck/chuck.js/app/Game/Channel/User.js:22:28

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:406:26)
    at PipeToChannel.sendToUser (/home/jeena/chuck/chuck.js/app/Server/PipeToChannel.js:52:13)
    at User.onGameCommand (/home/jeena/chuck/chuck.js/app/Server/User.js:74:26)
    at Object.Helper.applyCommand (/home/jeena/chuck/chuck.js/app/Lib/Utilities/Protocol/Helper.js:36:32)
    at User.onMessage (/home/jeena/chuck/chuck.js/app/Server/User.js:39:24)
    at Socket.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/namespace.js:353:20)
    at Manager.onClientMessage (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/manager.js:469:38)
    at WebSocket.Transport.onMessage (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/jeena/chuck/chuck.js/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)

npm ERR! chuck.js@0.1.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the chuck.js@0.1.0 start script.
npm ERR! This is most likely a problem with the chuck.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chuck.js
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.9.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/jeena/chuck/chuck.js
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jeena/chuck/chuck.js/npm-debug.log
npm ERR! not ok code 0
```
